// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.0
// source: applications/auth/proto/auth.proto

package auth

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	enums "mcp/core/enums"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Claims struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Permissions   []enums.Permission     `protobuf:"varint,2,rep,packed,name=permissions,proto3,enum=enums.Permission" json:"permissions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Claims) Reset() {
	*x = Claims{}
	mi := &file_applications_auth_proto_auth_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Claims) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Claims) ProtoMessage() {}

func (x *Claims) ProtoReflect() protoreflect.Message {
	mi := &file_applications_auth_proto_auth_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Claims.ProtoReflect.Descriptor instead.
func (*Claims) Descriptor() ([]byte, []int) {
	return file_applications_auth_proto_auth_proto_rawDescGZIP(), []int{0}
}

func (x *Claims) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *Claims) GetPermissions() []enums.Permission {
	if x != nil {
		return x.Permissions
	}
	return nil
}

type IssueAccessTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Permissions   []enums.Permission     `protobuf:"varint,2,rep,packed,name=permissions,proto3,enum=enums.Permission" json:"permissions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IssueAccessTokenRequest) Reset() {
	*x = IssueAccessTokenRequest{}
	mi := &file_applications_auth_proto_auth_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IssueAccessTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IssueAccessTokenRequest) ProtoMessage() {}

func (x *IssueAccessTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_applications_auth_proto_auth_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IssueAccessTokenRequest.ProtoReflect.Descriptor instead.
func (*IssueAccessTokenRequest) Descriptor() ([]byte, []int) {
	return file_applications_auth_proto_auth_proto_rawDescGZIP(), []int{1}
}

func (x *IssueAccessTokenRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *IssueAccessTokenRequest) GetPermissions() []enums.Permission {
	if x != nil {
		return x.Permissions
	}
	return nil
}

type IssueAccessTokenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccessToken   string                 `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IssueAccessTokenResponse) Reset() {
	*x = IssueAccessTokenResponse{}
	mi := &file_applications_auth_proto_auth_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IssueAccessTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IssueAccessTokenResponse) ProtoMessage() {}

func (x *IssueAccessTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_applications_auth_proto_auth_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IssueAccessTokenResponse.ProtoReflect.Descriptor instead.
func (*IssueAccessTokenResponse) Descriptor() ([]byte, []int) {
	return file_applications_auth_proto_auth_proto_rawDescGZIP(), []int{2}
}

func (x *IssueAccessTokenResponse) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

type DeleteAccessTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccessToken   string                 `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteAccessTokenRequest) Reset() {
	*x = DeleteAccessTokenRequest{}
	mi := &file_applications_auth_proto_auth_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteAccessTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAccessTokenRequest) ProtoMessage() {}

func (x *DeleteAccessTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_applications_auth_proto_auth_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAccessTokenRequest.ProtoReflect.Descriptor instead.
func (*DeleteAccessTokenRequest) Descriptor() ([]byte, []int) {
	return file_applications_auth_proto_auth_proto_rawDescGZIP(), []int{3}
}

func (x *DeleteAccessTokenRequest) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

type DeleteAccessTokenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteAccessTokenResponse) Reset() {
	*x = DeleteAccessTokenResponse{}
	mi := &file_applications_auth_proto_auth_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteAccessTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAccessTokenResponse) ProtoMessage() {}

func (x *DeleteAccessTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_applications_auth_proto_auth_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAccessTokenResponse.ProtoReflect.Descriptor instead.
func (*DeleteAccessTokenResponse) Descriptor() ([]byte, []int) {
	return file_applications_auth_proto_auth_proto_rawDescGZIP(), []int{4}
}

type VerifyAccessTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccessToken   string                 `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyAccessTokenRequest) Reset() {
	*x = VerifyAccessTokenRequest{}
	mi := &file_applications_auth_proto_auth_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyAccessTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyAccessTokenRequest) ProtoMessage() {}

func (x *VerifyAccessTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_applications_auth_proto_auth_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyAccessTokenRequest.ProtoReflect.Descriptor instead.
func (*VerifyAccessTokenRequest) Descriptor() ([]byte, []int) {
	return file_applications_auth_proto_auth_proto_rawDescGZIP(), []int{5}
}

func (x *VerifyAccessTokenRequest) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

type VerifyAccessTokenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Claims        *Claims                `protobuf:"bytes,1,opt,name=claims,proto3" json:"claims,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyAccessTokenResponse) Reset() {
	*x = VerifyAccessTokenResponse{}
	mi := &file_applications_auth_proto_auth_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyAccessTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyAccessTokenResponse) ProtoMessage() {}

func (x *VerifyAccessTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_applications_auth_proto_auth_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyAccessTokenResponse.ProtoReflect.Descriptor instead.
func (*VerifyAccessTokenResponse) Descriptor() ([]byte, []int) {
	return file_applications_auth_proto_auth_proto_rawDescGZIP(), []int{6}
}

func (x *VerifyAccessTokenResponse) GetClaims() *Claims {
	if x != nil {
		return x.Claims
	}
	return nil
}

type IssueRefreshTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Permissions   []enums.Permission     `protobuf:"varint,2,rep,packed,name=permissions,proto3,enum=enums.Permission" json:"permissions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IssueRefreshTokenRequest) Reset() {
	*x = IssueRefreshTokenRequest{}
	mi := &file_applications_auth_proto_auth_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IssueRefreshTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IssueRefreshTokenRequest) ProtoMessage() {}

func (x *IssueRefreshTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_applications_auth_proto_auth_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IssueRefreshTokenRequest.ProtoReflect.Descriptor instead.
func (*IssueRefreshTokenRequest) Descriptor() ([]byte, []int) {
	return file_applications_auth_proto_auth_proto_rawDescGZIP(), []int{7}
}

func (x *IssueRefreshTokenRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *IssueRefreshTokenRequest) GetPermissions() []enums.Permission {
	if x != nil {
		return x.Permissions
	}
	return nil
}

type IssueRefreshTokenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RefreshToken  string                 `protobuf:"bytes,1,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IssueRefreshTokenResponse) Reset() {
	*x = IssueRefreshTokenResponse{}
	mi := &file_applications_auth_proto_auth_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IssueRefreshTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IssueRefreshTokenResponse) ProtoMessage() {}

func (x *IssueRefreshTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_applications_auth_proto_auth_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IssueRefreshTokenResponse.ProtoReflect.Descriptor instead.
func (*IssueRefreshTokenResponse) Descriptor() ([]byte, []int) {
	return file_applications_auth_proto_auth_proto_rawDescGZIP(), []int{8}
}

func (x *IssueRefreshTokenResponse) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

type DeleteRefreshTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RefreshToken  string                 `protobuf:"bytes,1,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRefreshTokenRequest) Reset() {
	*x = DeleteRefreshTokenRequest{}
	mi := &file_applications_auth_proto_auth_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRefreshTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRefreshTokenRequest) ProtoMessage() {}

func (x *DeleteRefreshTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_applications_auth_proto_auth_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRefreshTokenRequest.ProtoReflect.Descriptor instead.
func (*DeleteRefreshTokenRequest) Descriptor() ([]byte, []int) {
	return file_applications_auth_proto_auth_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteRefreshTokenRequest) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

type DeleteRefreshTokenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRefreshTokenResponse) Reset() {
	*x = DeleteRefreshTokenResponse{}
	mi := &file_applications_auth_proto_auth_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRefreshTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRefreshTokenResponse) ProtoMessage() {}

func (x *DeleteRefreshTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_applications_auth_proto_auth_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRefreshTokenResponse.ProtoReflect.Descriptor instead.
func (*DeleteRefreshTokenResponse) Descriptor() ([]byte, []int) {
	return file_applications_auth_proto_auth_proto_rawDescGZIP(), []int{10}
}

type VerifyRefreshTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RefreshToken  string                 `protobuf:"bytes,1,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyRefreshTokenRequest) Reset() {
	*x = VerifyRefreshTokenRequest{}
	mi := &file_applications_auth_proto_auth_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyRefreshTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyRefreshTokenRequest) ProtoMessage() {}

func (x *VerifyRefreshTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_applications_auth_proto_auth_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyRefreshTokenRequest.ProtoReflect.Descriptor instead.
func (*VerifyRefreshTokenRequest) Descriptor() ([]byte, []int) {
	return file_applications_auth_proto_auth_proto_rawDescGZIP(), []int{11}
}

func (x *VerifyRefreshTokenRequest) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

type VerifyRefreshTokenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Claims        *Claims                `protobuf:"bytes,1,opt,name=claims,proto3" json:"claims,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyRefreshTokenResponse) Reset() {
	*x = VerifyRefreshTokenResponse{}
	mi := &file_applications_auth_proto_auth_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyRefreshTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyRefreshTokenResponse) ProtoMessage() {}

func (x *VerifyRefreshTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_applications_auth_proto_auth_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyRefreshTokenResponse.ProtoReflect.Descriptor instead.
func (*VerifyRefreshTokenResponse) Descriptor() ([]byte, []int) {
	return file_applications_auth_proto_auth_proto_rawDescGZIP(), []int{12}
}

func (x *VerifyRefreshTokenResponse) GetClaims() *Claims {
	if x != nil {
		return x.Claims
	}
	return nil
}

var File_applications_auth_proto_auth_proto protoreflect.FileDescriptor

const file_applications_auth_proto_auth_proto_rawDesc = "" +
	"\n" +
	"\"applications/auth/proto/auth.proto\x12\aauth.v1\x1a\x1bcore/proto/permission.proto\x1a\x1cgoogle/api/annotations.proto\"V\n" +
	"\x06Claims\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\x123\n" +
	"\vpermissions\x18\x02 \x03(\x0e2\x11.enums.PermissionR\vpermissions\"g\n" +
	"\x17IssueAccessTokenRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\x123\n" +
	"\vpermissions\x18\x02 \x03(\x0e2\x11.enums.PermissionR\vpermissions\"=\n" +
	"\x18IssueAccessTokenResponse\x12!\n" +
	"\faccess_token\x18\x01 \x01(\tR\vaccessToken\"=\n" +
	"\x18DeleteAccessTokenRequest\x12!\n" +
	"\faccess_token\x18\x01 \x01(\tR\vaccessToken\"\x1b\n" +
	"\x19DeleteAccessTokenResponse\"=\n" +
	"\x18VerifyAccessTokenRequest\x12!\n" +
	"\faccess_token\x18\x01 \x01(\tR\vaccessToken\"D\n" +
	"\x19VerifyAccessTokenResponse\x12'\n" +
	"\x06claims\x18\x01 \x01(\v2\x0f.auth.v1.ClaimsR\x06claims\"h\n" +
	"\x18IssueRefreshTokenRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\x123\n" +
	"\vpermissions\x18\x02 \x03(\x0e2\x11.enums.PermissionR\vpermissions\"@\n" +
	"\x19IssueRefreshTokenResponse\x12#\n" +
	"\rrefresh_token\x18\x01 \x01(\tR\frefreshToken\"@\n" +
	"\x19DeleteRefreshTokenRequest\x12#\n" +
	"\rrefresh_token\x18\x01 \x01(\tR\frefreshToken\"\x1c\n" +
	"\x1aDeleteRefreshTokenResponse\"@\n" +
	"\x19VerifyRefreshTokenRequest\x12#\n" +
	"\rrefresh_token\x18\x01 \x01(\tR\frefreshToken\"E\n" +
	"\x1aVerifyRefreshTokenResponse\x12'\n" +
	"\x06claims\x18\x01 \x01(\v2\x0f.auth.v1.ClaimsR\x06claims2\x98\x06\n" +
	"\vAuthService\x12y\n" +
	"\x10IssueAccessToken\x12 .auth.v1.IssueAccessTokenRequest\x1a!.auth.v1.IssueAccessTokenResponse\" \x82\xd3\xe4\x93\x02\x1a:\x01*\"\x15/v1/auth/access-token\x12|\n" +
	"\x11DeleteAccessToken\x12!.auth.v1.DeleteAccessTokenRequest\x1a\".auth.v1.DeleteAccessTokenResponse\" \x82\xd3\xe4\x93\x02\x1a:\x01**\x15/v1/auth/access-token\x12\x83\x01\n" +
	"\x11VerifyAccessToken\x12!.auth.v1.VerifyAccessTokenRequest\x1a\".auth.v1.VerifyAccessTokenResponse\"'\x82\xd3\xe4\x93\x02!:\x01*\"\x1c/v1/auth/verify-access-token\x12}\n" +
	"\x11IssueRefreshToken\x12!.auth.v1.IssueRefreshTokenRequest\x1a\".auth.v1.IssueRefreshTokenResponse\"!\x82\xd3\xe4\x93\x02\x1b:\x01*\"\x16/v1/auth/refresh-token\x12\x80\x01\n" +
	"\x12DeleteRefreshToken\x12\".auth.v1.DeleteRefreshTokenRequest\x1a#.auth.v1.DeleteRefreshTokenResponse\"!\x82\xd3\xe4\x93\x02\x1b:\x01**\x16/v1/auth/refresh-token\x12\x87\x01\n" +
	"\x12VerifyRefreshToken\x12\".auth.v1.VerifyRefreshTokenRequest\x1a#.auth.v1.VerifyRefreshTokenResponse\"(\x82\xd3\xe4\x93\x02\":\x01*\"\x1d/v1/auth/verify-refresh-tokenB\bZ\x06./authb\x06proto3"

var (
	file_applications_auth_proto_auth_proto_rawDescOnce sync.Once
	file_applications_auth_proto_auth_proto_rawDescData []byte
)

func file_applications_auth_proto_auth_proto_rawDescGZIP() []byte {
	file_applications_auth_proto_auth_proto_rawDescOnce.Do(func() {
		file_applications_auth_proto_auth_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_applications_auth_proto_auth_proto_rawDesc), len(file_applications_auth_proto_auth_proto_rawDesc)))
	})
	return file_applications_auth_proto_auth_proto_rawDescData
}

var file_applications_auth_proto_auth_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_applications_auth_proto_auth_proto_goTypes = []any{
	(*Claims)(nil),                     // 0: auth.v1.Claims
	(*IssueAccessTokenRequest)(nil),    // 1: auth.v1.IssueAccessTokenRequest
	(*IssueAccessTokenResponse)(nil),   // 2: auth.v1.IssueAccessTokenResponse
	(*DeleteAccessTokenRequest)(nil),   // 3: auth.v1.DeleteAccessTokenRequest
	(*DeleteAccessTokenResponse)(nil),  // 4: auth.v1.DeleteAccessTokenResponse
	(*VerifyAccessTokenRequest)(nil),   // 5: auth.v1.VerifyAccessTokenRequest
	(*VerifyAccessTokenResponse)(nil),  // 6: auth.v1.VerifyAccessTokenResponse
	(*IssueRefreshTokenRequest)(nil),   // 7: auth.v1.IssueRefreshTokenRequest
	(*IssueRefreshTokenResponse)(nil),  // 8: auth.v1.IssueRefreshTokenResponse
	(*DeleteRefreshTokenRequest)(nil),  // 9: auth.v1.DeleteRefreshTokenRequest
	(*DeleteRefreshTokenResponse)(nil), // 10: auth.v1.DeleteRefreshTokenResponse
	(*VerifyRefreshTokenRequest)(nil),  // 11: auth.v1.VerifyRefreshTokenRequest
	(*VerifyRefreshTokenResponse)(nil), // 12: auth.v1.VerifyRefreshTokenResponse
	(enums.Permission)(0),              // 13: enums.Permission
}
var file_applications_auth_proto_auth_proto_depIdxs = []int32{
	13, // 0: auth.v1.Claims.permissions:type_name -> enums.Permission
	13, // 1: auth.v1.IssueAccessTokenRequest.permissions:type_name -> enums.Permission
	0,  // 2: auth.v1.VerifyAccessTokenResponse.claims:type_name -> auth.v1.Claims
	13, // 3: auth.v1.IssueRefreshTokenRequest.permissions:type_name -> enums.Permission
	0,  // 4: auth.v1.VerifyRefreshTokenResponse.claims:type_name -> auth.v1.Claims
	1,  // 5: auth.v1.AuthService.IssueAccessToken:input_type -> auth.v1.IssueAccessTokenRequest
	3,  // 6: auth.v1.AuthService.DeleteAccessToken:input_type -> auth.v1.DeleteAccessTokenRequest
	5,  // 7: auth.v1.AuthService.VerifyAccessToken:input_type -> auth.v1.VerifyAccessTokenRequest
	7,  // 8: auth.v1.AuthService.IssueRefreshToken:input_type -> auth.v1.IssueRefreshTokenRequest
	9,  // 9: auth.v1.AuthService.DeleteRefreshToken:input_type -> auth.v1.DeleteRefreshTokenRequest
	11, // 10: auth.v1.AuthService.VerifyRefreshToken:input_type -> auth.v1.VerifyRefreshTokenRequest
	2,  // 11: auth.v1.AuthService.IssueAccessToken:output_type -> auth.v1.IssueAccessTokenResponse
	4,  // 12: auth.v1.AuthService.DeleteAccessToken:output_type -> auth.v1.DeleteAccessTokenResponse
	6,  // 13: auth.v1.AuthService.VerifyAccessToken:output_type -> auth.v1.VerifyAccessTokenResponse
	8,  // 14: auth.v1.AuthService.IssueRefreshToken:output_type -> auth.v1.IssueRefreshTokenResponse
	10, // 15: auth.v1.AuthService.DeleteRefreshToken:output_type -> auth.v1.DeleteRefreshTokenResponse
	12, // 16: auth.v1.AuthService.VerifyRefreshToken:output_type -> auth.v1.VerifyRefreshTokenResponse
	11, // [11:17] is the sub-list for method output_type
	5,  // [5:11] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_applications_auth_proto_auth_proto_init() }
func file_applications_auth_proto_auth_proto_init() {
	if File_applications_auth_proto_auth_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_applications_auth_proto_auth_proto_rawDesc), len(file_applications_auth_proto_auth_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_applications_auth_proto_auth_proto_goTypes,
		DependencyIndexes: file_applications_auth_proto_auth_proto_depIdxs,
		MessageInfos:      file_applications_auth_proto_auth_proto_msgTypes,
	}.Build()
	File_applications_auth_proto_auth_proto = out.File
	file_applications_auth_proto_auth_proto_goTypes = nil
	file_applications_auth_proto_auth_proto_depIdxs = nil
}
